# Generated by Django 5.2.3 on 2025-08-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
    ]
