version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000

  # Redis Cache (optional, for production caching)
  redis:
    image: redis:7-alpine
    container_name: corporate_mvp_redis
    ports:
      - "24798:6379"
    networks:
      - corporate_mvp_network
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  corporate_mvp_network:
    driver: bridge