# Generated by Django 5.2.3 on 2025-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=25, unique=True)),
                ("description", models.TextField()),
                ("source", models.URLField()),
                ("category", models.ManyToManyField(to="apis.coursecategory")),
            ],
        ),
    ]
