# Generated by Django 5.2.3 on 2025-07-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_coursecategory_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="title", field=models.TextField(unique=True),
        ),
    ]
