# Generated by Django 5.2.3 on 2025-08-23 15:16

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_coursecategory_project_criticality_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='source',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='courses', to='apis.coursecategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text="Type of content (e.g., 'project', 'employee', 'survey')", max_length=50)),
                ('content_id', models.CharField(help_text='ID of the source content', max_length=100)),
                ('title', models.CharField(help_text='Title or summary of the content', max_length=255)),
                ('content', models.TextField(help_text='Full text content for embedding')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, help_text='Vector embedding of the content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for filtering and context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_base',
                'indexes': [models.Index(fields=['content_type'], name='knowledge_b_content_afd6be_idx'), models.Index(fields=['content_id'], name='knowledge_b_content_5ed04b_idx'), models.Index(fields=['created_at'], name='knowledge_b_created_720dcc_idx')],
            },
        ),
    ]
