# Generated by Django 5.2.3 on 2025-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_course_source_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding',
            field=models.TextField(help_text='Vector embedding of the content stored as JSON'),
        ),
    ]
