# Generated by Django 5.2.3 on 2025-09-02 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_conversation_conversationmessage_conversationshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='apis.project'),
        ),
    ]
