# Generated by Django 5.2.3 on 2025-09-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_projectallocation_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectallocation',
            name='criticality',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
