# Generated by Django 5.2.3 on 2025-09-21 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_projectallocation_criticality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_departments',
            field=models.JSONField(blank=True, help_text='List of department names for department targeting', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_employees',
            field=models.ManyToManyField(blank=True, help_text='Specific employees for custom targeting', related_name='targeted_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_risk_levels',
            field=models.JSONField(blank=True, help_text="List of risk levels: ['High', 'Medium', 'Low'] for risk targeting", null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_roles',
            field=models.JSONField(blank=True, help_text="List of roles: ['manager', 'associate'] for role targeting", null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Employees'), ('team', 'My Team Only'), ('department', 'By Department'), ('role', 'By Role'), ('risk_level', 'By Risk Level'), ('custom', 'Custom Selection')], default='all', max_length=20),
        ),
    ]
