# Generated by Django 5.2.3 on 2025-09-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_survey_target_departments_survey_target_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(default='https://example.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
