# Generated by Django 5.2.3 on 2025-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_course_source_alter_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='source',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='talent_type',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
