# Generated by Django 5.2.3 on 2025-10-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_course_source_employeeprofile_talent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_project_criticality',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='suggested_risk',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
