# Generated by Django 5.2.3 on 2025-10-17 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_attrition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attrition',
            unique_together={('manager', 'year', 'month')},
        ),
    ]
