# Generated by Django 5.2.3 on 2025-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_alter_attrition_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrition',
            name='month',
            field=models.IntegerField(),
        ),
    ]
