# Generated by Django 5.2.3 on 2025-10-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_attrition_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('primary_trigger', models.CharField(blank=True, choices=[('MH', 'Mental Health'), ('MT', 'Motivation Factor'), ('CO', 'Career Opportunities'), ('PR', 'Personal Reason')], max_length=2, null=True)),
            ],
        ),
    ]
