# Generated by Django 5.2.3 on 2025-10-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='all_triggers',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='all_triggers',
            field=models.ManyToManyField(to='apis.trigger'),
        ),
    ]
